"""
Django settings for kavi_bazaar project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from the project root regardless of the current working directory.
# Note: existing environment variables always win over .env values.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Set DJANGO_SECRET_KEY via the environment (or .env). The fallback below is
# only a local-development placeholder and is never safe for production.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or 'django-insecure-local-dev-only-do-not-use-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').strip().lower() in ('1', 'true', 'yes', 'on')

# Fail fast if production would run with the placeholder secret key.
if not DEBUG and SECRET_KEY == 'django-insecure-local-dev-only-do-not-use-in-production':
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set when DEBUG is False.')

# ALLOWED_HOSTS is configurable via DJANGO_ALLOWED_HOSTS (comma-separated).
# Defaults cover local development (127.0.0.1, localhost).
#
# Railway health checks are sent with the Host header 'healthcheck.railway.app',
# so that host is always allowed.
#
# Railway exposes the generated *.up.railway.app domain as RAILWAY_PUBLIC_DOMAIN;
# it is appended automatically so the public domain works without hardcoding a
# specific hostname.
_DEFAULT_ALLOWED_HOSTS = '127.0.0.1,localhost'
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', _DEFAULT_ALLOWED_HOSTS).split(',') if h.strip()]
if 'healthcheck.railway.app' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('healthcheck.railway.app')
_RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '').strip().lower()
if _RAILWAY_PUBLIC_DOMAIN and _RAILWAY_PUBLIC_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_RAILWAY_PUBLIC_DOMAIN)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'kavi_bazaar.middleware.MediaCacheMiddleware',
]

ROOT_URLCONF = 'kavi_bazaar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_count',
                'shop.context_processors.profile_picture',
                'shop.context_processors.dashboard_access',
                'shop.context_processors.search_scope',
                'shop.context_processors.unread_notifications_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'kavi_bazaar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import dj_database_url
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
#
# Project-level source static lives in <project root>/static (committed to git)
# and is picked up via STATICFILES_DIRS. App-level source lives in
# shop/static/ and is auto-discovered. collectstatic merges both into
# STATIC_ROOT (staticfiles/), which WhiteNoise serves in production.
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/images/'
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Razorpay - read from env/.env. Leave unset to run in demo/mock mode.
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')

# Google Maps
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')

# Google Sign-In (OAuth 2.0) - create an OAuth 2.0 Web client ID in Google Cloud Console
# and set GOOGLE_CLIENT_ID / GOOGLE_CLIENT_SECRET in .env (never hardcode these).
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')

# Email (Gmail SMTP) - use a Gmail App Password, NOT your normal Gmail password.
# When no SMTP password is configured, fall back to the console backend so
# local development still works without credentials.
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'kavibazaar@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
if EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF Trusted Origins - defaults cover local development; the Railway public
# domain is appended automatically when deployed.
_CSRF_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1,http://localhost').split(',') if o.strip()]
if _RAILWAY_PUBLIC_DOMAIN:
    _https_origin = 'https://' + _RAILWAY_PUBLIC_DOMAIN
    if _https_origin not in _CSRF_ORIGINS:
        _CSRF_ORIGINS.append(_https_origin)
CSRF_TRUSTED_ORIGINS = _CSRF_ORIGINS

# Production security flags - only enabled when DEBUG is off. Railway terminates
# TLS at the edge, so Django must trust the X-Forwarded-Proto header.
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SECURE_SSL_REDIRECT', 'True').strip().lower() in ('1', 'true', 'yes', 'on')
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
else:
    SECURE_SSL_REDIRECT = False


# ─────────────────────────────────────────────────────────────
# Jazzmin (Django admin) — Premium dark-luxury theme
# ─────────────────────────────────────────────────────────────
JAZZMIN_SETTINGS = {
    'site_title': 'Kavi Bazaar Admin',
    'site_header': 'Kavi Bazaar',
    'site_brand': 'Kavi Bazaar',
    'site_logo': 'shop/admin_brand.svg',
    'site_logo_classes': '',
    'site_icon': 'shop/favicon.png',
    'welcome_sign': 'Welcome back to Kavi Bazaar Admin',
    'copyright': 'Kavi Bazaar',
    'search_model': ['auth.User', 'shop.Product', 'shop.Order'],
    'user_avatar': None,
    'topmenu_links': [
        {'name': 'KaviBazaar Admin', 'url': '/dashboard/'},
    ],
    'show_sidebar': True,
    'navigation_expanded': True,
    'hide_apps': [],
    'hide_models': [],
    'order_with_respect_to': ['auth', 'shop'],
    'custom_links': {},
    'icons': {
        'auth': 'fas fa-crown',
        'auth.user': 'fas fa-user-cog',
        'auth.Group': 'fas fa-users',
        'shop.Product': 'fas fa-box-open',
        'shop.Catagory': 'fas fa-tags',
        'shop.Order': 'fas fa-receipt',
        'shop.OrderItem': 'fas fa-list-ol',
        'shop.Payment': 'fas fa-credit-card',
        'shop.Cart': 'fas fa-shopping-cart',
        'shop.Favourite': 'fas fa-heart',
        'shop.UserProfile': 'fas fa-id-badge',
        'shop.LoginOTP': 'fas fa-shield-alt',
        'shop.SavedAddress': 'fas fa-map-marker-alt',
    },
    'default_icon_parents': 'fas fa-chevron-circle-right',
    'default_icon_children': 'fas fa-circle',
    'related_modal_active': True,
    'custom_css': 'shop/admin_premium.css',
    'custom_js': 'shop/admin_premium.js',
    'use_google_fonts_cdn': False,
    'show_ui_builder': False,
    'show_theme_chooser': False,
    'changeform_format': 'horizontal_tabs',
    'changeform_format_overrides': {'shop.Product': 'single'},
    'language_chooser': False,
}

JAZZMIN_UI_TWEAKS = {
    'navbar_small_text': False,
    'footer_small_text': False,
    'body_small_text': False,
    'brand_small_text': False,
    'brand_colour': 'navbar-dark',
    'accent': 'accent-primary',
    'navbar': 'navbar-dark navbar-dark',
    'no_navbar_border': True,
    'navbar_fixed': True,
    'layout_boxed': False,
    'footer_fixed': False,
    'sidebar_fixed': True,
    'sidebar': 'sidebar-dark-primary',
    'sidebar_nav_small_text': False,
    'sidebar_disable_expand': False,
    'sidebar_nav_child_indent': True,
    'sidebar_nav_compact_style': False,
    'sidebar_nav_legacy_style': False,
    'sidebar_nav_flat_style': False,
    'theme': 'darkly',
    'default_theme_mode': 'dark',
    'button_classes': {
        'primary': 'btn-primary',
        'secondary': 'btn-secondary',
        'info': 'btn-info',
        'warning': 'btn-warning',
        'danger': 'btn-danger',
        'success': 'btn-success',
    },
}

