# Generated by Django 6.0.4 on 2026-04-17 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_latest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Latest',
        ),
    ]
