# Generated by Django 6.0.4 on 2026-08-01 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_loginotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
