# Generated by Django 6.0.4 on 2026-08-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
