# Generated by Django 6.0.4 on 2026-08-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_alternate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cod_available',
            field=models.BooleanField(default=True, help_text='Yes-Cash on Delivery available for this product'),
        ),
    ]
