# Generated by Django 6.0.4 on 2026-08-01 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_savedaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cod_available',
        ),
    ]
