# Generated by Django 6.0.4 on 2026-08-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_product_cod_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dashboard_access',
            field=models.BooleanField(default=True, verbose_name='Dashboard access'),
        ),
    ]
