# Generated by Django 6.0.4 on 2026-08-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_userprofile_dashboard_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highlight_1',
            field=models.CharField(blank=True, default='100% Genuine product from Flipkart', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='highlight_2',
            field=models.CharField(blank=True, default='7-day replacement guarantee', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='highlight_3',
            field=models.CharField(blank=True, default='Secure payment & on-time delivery', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='perk_1_icon',
            field=models.CharField(blank=True, default='fa-truck', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='perk_1_sub',
            field=models.CharField(blank=True, default='2–4 business days', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='perk_1_title',
            field=models.CharField(blank=True, default='Free delivery', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='perk_2_icon',
            field=models.CharField(blank=True, default='fa-rotate-left', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='perk_2_sub',
            field=models.CharField(blank=True, default='Hassle-free', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='perk_2_title',
            field=models.CharField(blank=True, default='7-day returns', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='perk_3_icon',
            field=models.CharField(blank=True, default='fa-shield', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='perk_3_sub',
            field=models.CharField(blank=True, default='100% protected', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='perk_3_title',
            field=models.CharField(blank=True, default='Secure payment', max_length=100),
        ),
    ]
