# Generated by Django 6.0.4 on 2026-08-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ratings/'),
        ),
    ]
