# Generated by Django 6.0.4 on 2026-08-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_productrating_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When the order was marked Delivered', null=True),
        ),
    ]
