# Generated by Django 6.0.4 on 2026-08-03 06:28

import datetime
from django.db import migrations, models


def add_business_days(start, days):
    result = start
    added = 0
    while added < days:
        result += datetime.timedelta(days=1)
        if result.weekday() < 5:
            added += 1
    return result


def backfill_expected_delivery(apps, schema_editor):
    Order = apps.get_model('shop', 'Order')
    for order in Order.objects.filter(expected_delivery_date__isnull=True):
        base = order.created_at or datetime.datetime.now(datetime.timezone.utc)
        order.expected_delivery_date = add_business_days(base, 4).date()
        order.save(update_fields=['expected_delivery_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Estimated delivery date shown to the customer', null=True),
        ),
        migrations.RunPython(backfill_expected_delivery, migrations.RunPython.noop),
    ]
