# Generated by Django 6.0.4 on 2026-08-04 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_order_pincode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productrating',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shop.orderitem'),
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('product', 'user', 'order_item')},
        ),
    ]
