# Generated by Django 6.0.4 on 2026-08-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_productratingmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cod_available',
            field=models.BooleanField(default=True, help_text='Cash on Delivery available for this product'),
        ),
    ]
