# Generated by Django 6.0.4 on 2026-08-05 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_product_cash_on_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('out_for_delivery', 'Out for Delivery'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('order_refunded', 'Order Refunded'), ('refund_completed', 'Refund Completed'), ('return_approved', 'Return Request Approved'), ('return_rejected', 'Return Request Rejected'), ('back_in_stock', 'Back in Stock'), ('wishlist_back_in_stock', 'Wishlist Item Back in Stock'), ('price_drop', 'Price Drop'), ('login_new_device', 'New Device Login'), ('password_changed', 'Password Changed'), ('email_verified', 'Email Verified'), ('announcement', 'Admin Announcement')], max_length=50)),
                ('icon', models.CharField(blank=True, default='fa-bell', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('link', models.CharField(blank=True, default='', help_text='Optional URL opened when the notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
