# Generated by Django 6.0.4 on 2026-08-05 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('order_date', models.DateTimeField()),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('payment_status', models.CharField(blank=True, default='', max_length=50)),
                ('order_status', models.CharField(blank=True, default='', max_length=50)),
                ('subtotal', models.FloatField(default=0.0, help_text='Sum of MRP totals')),
                ('total_discount', models.FloatField(default=0.0, help_text='Total savings vs MRP')),
                ('delivery_charge', models.FloatField(default=0.0)),
                ('tax_amount', models.FloatField(default=0.0)),
                ('grand_total', models.FloatField(default=0.0)),
                ('line_items', models.JSONField(default=list, help_text='Snapshot of products, qty, prices and images at purchase time')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='shop.order')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
